### ISSUE TITLE
Files screen: error when renaming file

### ISSUE THREAD

**Issue by akimoto72738** [ipfs-shipyard/ipfs-webui#1537]
Browser throws exception

```
TypeError: r[0].flat is not a function
    at utils.js:22
    at c (runtime.js:45)
    at Generator._invoke (runtime.js:271)
    at Generator.S.forEach.e.<computed> [as next] (runtime.js:97)
    at c (runtime.js:45)
    at t (runtime.js:135)
    at runtime.js:145
```

my browser：Chrome 83.0.4103.116/firefox 78.0.1

**Comment by akimoto72738** [comment]
ipfs web ui version 2.10.1

**Comment by akimoto72738** [comment]
ipfs version 0.6.0，this error occur since i update ipfs to 0.6.0。

**Comment by jessicaschilling** [comment]
@olizilla, might you be able to triage? Thanks!

**Comment by lidel** [comment]
I can confirm, I was about to fill this myself.

## Bug summary

There is a bug when user renames a file. 
File is renamed, but an error occurs in the console and error notification is displayed:

> ![renaming-file-triggers-false-error-2020-07-02--18-03-35](https://user-images.githubusercontent.com/157609/86384261-c97cd200-bc8e-11ea-9360-49dfdb374502.png)

I was able to reproduce this in Firefox and go-ipfs 0.6.0

**Comment by akimoto72738** [comment]
UPDATE: This error will be threw also when import a ipfs hash（cid）.
Looks like it is a same exception "TypeError: r[0].flat is not a function"
![捕获](https://user-images.githubusercontent.com/67720156/86423939-b829d900-bd13-11ea-8a72-ffaba7e9f549.jpg)
![捕获1](https://user-images.githubusercontent.com/67720156/86423948-c24bd780-bd13-11ea-8a2f-36713e6c22f5.JPG)

**Comment by rafaelramalho19** [comment]
I believe this was fixed by https://github.com/ipfs-shipyard/ipfs-webui/pull/1589, can't replicate anymore.

**Comment by lidel** [comment]
I think you meant #1569 ? Anyway, yes, its fixed in master, so closing it :+1:
